// olytag - Olympia: The Age of Gods
//
// Copyright (c) 2022 by the OlyTag authors.
// Please see the LICENSE file in the root directory of this repository for further information.

#ifndef OLYTAG_FORWARD_H
#define OLYTAG_FORWARD_H

#include <stdio.h>
#include "types.h"
#include "vectors/ilist.h"

void add_aura(int who, int aura);
void add_unformed_sup(int pl);
void add_new_players();
void add_piety(int who, int amount, int use_limit);
void add_scrolls(int where);
void add_skill_experience(int who, int skill);
void alert_scry_attempt(int who, int target, char *s);
void alert_scry_generic(int who, int where);
void alert_palantir_scry(int who, int target);
void all_stack(int who, ilist *l);
int alone_here(int who);
int artifact_identify(char *header, struct command *c);
void auto_hades(void);
void auto_savage(int who);
void auto_undead(int who);
int autocharge(int who, int total);
int beast_wild(int who);
int being_taught(int who, int a1, int *item, int *bonus);
int building_owner(int ship);
int calc_beast_limit(int who, int boolean);
int calc_entrance_fee(struct loc_control_ent *control, struct command *c, int ruler);
int calc_man_limit(int who, int boolean);
void calculate_nation_nps();
void call_init_routines();
int can_join_guild(int who, int school);
int cast_check_char_here(int who, int target);
int cast_where(int who);
void change_box_subkind(int where, int kind);
int char_here(int who, int a1);
void char_reclaim(int who);
char *char_rep_location(int who);
void char_rep_sup(int i, int n);
void character_report();
int charge_entrance_fees(int who, int owner, int amount);
void check_all_auto_attacks();
void check_captain_loses_sailors(int qty, int target, int who);
void check_db();
void check_ocean_chars();
int check_skill(int who, int skill);
void check_win_conditions();
void clear_all_att(int who);
void clear_all_trades(int where);
void clear_contacts(int who);
void clear_guard_flag(int loser);
void clear_second_waits();
void clear_wait_parse(struct command *);
int cloak_lord(int who);
void close_logfile();
void cmd_shift(struct command *c);
int combat_artifact_bonus(int unit, int n, int *item);
int combat_comp(const void *q1, const void *q2);
void command_done(struct command *c);
void compute_dist();
void connect_locations(int loc1, int dir1, int loc2, int dir2);
int contacted(int target, int who);
int controlled_humans_here(int province);
int controls_loc(int destination);
int count_any(int unit, int b, int c);
int count_any_real(int unit, int b, int c);
int count_fighters(int who, int item);
int count_stack_any(int who);
int count_stack_any_real(int who, int ignore_ninjas, int ignore_angels);
void create_cloudlands();
void create_faery();
void create_hades();
int create_monster_stack(int item, int qty, int where);
int create_new_beasts(int where, int sk);
int create_peasant_mob(int where);
int create_random_artifact(int monster);
int crosses_ocean(int target, int who);
int d_npc_breed(struct command *c);
int d_use_item(struct command *c);
void daily_events();
void delete_all_effects(int what, int type, int sk);
void delete_city_trade(int where, int item);
void deliver_lore(int pl, int a);
char *deserted_s(int n);
void determine_output_order();
void dissipate_storm(int i, int boolean);
void do_command(struct command *c);
int do_db_url(struct command *c);
void do_npc_orders(int new, int j, int k);
void do_production(int i, int boolean);
int do_rules_url(struct command *c);
void do_times();
void do_wild_hunt(int where);
void eat_loop(int mail_now);
int effective_workers(int who);
void experience_use_speedup(struct command *c);
char *extra_item_info(int who, int item, int qty);
void extract_stacked_unit(int who);
int find_command(char *cmd);
int find_nation(char *name);
struct trade *find_trade(int i, int n, int item);
int find_use_entry(int i);
int finish_command(struct command *c);
int first_character(int where);
int fort_default_defense(int subloc);
void float_cloudlands();
void flush_unit_orders(int old_pl, int who);
int garrison_here(int where);
int garrison_spot_check(int garr, int target);
void garrison_summary(int pl);
void gen_include_section();
void gen_include_sup(int eat_pl);
void generate_one_treasure(int who);
void generate_treasure(int n, int i);
void get_rid_of_collapsed_mine(int i);
void glob_init();
void gm_report(int gm_player);
void gm_show_all_skills(int skill_player, int boolean);
int has_city(int where);
int has_holy_plant(int who);
int has_holy_symbol(int who);
int here_pos(int winner);
int hinder_med_chance(int who);
void hinder_med_omen(int target, int who);
int how_many(int who1, int who2, int item, int qty, int have_left);
int i_generic_harvest(struct command *c, struct harvest *t);
int i_generic_make(struct command *c, struct make *t);
int i_repair(struct command *c);
void immediate_commands();
int int_comp(const void *q1, const void *q2);
void init_collect_list();
void init_load_sup(int who);
void init_locs_touched();
void init_lower();
void init_ocean_chars();
void init_random();
void init_savage_attacks();
void init_spaces();
void init_weather_views();
int inv_item_comp(const void *, const void *); //struct item_ent **, struct item_ent **
int is_defend(int who, int target);
int is_hostile(int ruler, int who);
int is_port_city(int where);
int item_fly_cap(int item);
int item_land_cap(int item);
int item_ride_cap(int item);
int item_weight(int item);
int join_guild(int who, int school);
void list_order_templates();
void list_partial_skills(int who, int who2, char *s);
void list_pending_trades(int who, int num);
void list_skill_sup(int who, struct skill_ent *e, char *prefix);
int load_cmap_players();
void load_db();
int loc_contains_hidden(int target);
int loc_depth(int i);
int loc_target(int target);
void location_production();
void lock_tag();
void log_output(int code, char *format, ...);
int los_province_distance(int who, int i);
long MM(int item);
void mail_reports();
void make_tower_guild(int new, int skill);
int market_here(int where);
void market_report(int who, int where);
void match_all_trades();
int mine_depth(int where);
void move_stack(int who, int where);
void my_free(void *ptr);
void *my_malloc(unsigned size);
void *my_realloc(void *ptr, unsigned size);
char *nation_s(int n);
void natural_weather();
int near_rocky_coast(int loc);
int nearby_grave(int province);
void new_player_top(int mail_now);
int new_potion(int who);
int new_suffuse_ring(int where);
struct trade *new_trade(int who, int kind, int item);
int next_np_turn(int pl);
void notify_loc_shroud(int where);
char *np_req_s(int skill);
void npc_move(int who);
int nps_invested(int who);
int oly_parse(struct command *c, char *cmd);
int oly_parse_cmd(struct command *, char *);
void open_faery_hill(int subloc);
void open_logfile();
void open_logfile_nondestruct();
void open_times();
void opium_market_delta(int where);
void orders_template(int i, int n);
void out(int who, char *format, ...);
int parse_arg(int who, char *s);
char *parse_wait_args(struct command *);
int peaceful_enter(int who, int where, int destination);
int pick_starting_city(int nation, int n);
void ping_garrisons();
int place_here(int where, int who);
void player_banner();
int player_controls_loc(int where);
void player_ent_info();
void player_report();
void player_report_sup(int who);
void post_month();
void post_production();
void pre_month();
void print_admit(int pl);
void print_att(int who, int num);
void print_dot(int ch);
void print_hiring_status(int pl);
void print_map(FILE *fp);
void print_unformed(int pl);
void prisoner_movement_escape_check(int who);
void process_orders();
int province_gate_here(int where);
int province_admin(int i);
int province_subloc(int i, int subloc);
void put_back_cookie(int who);
void queue(int who, char *format, ...);
void queue_npc_orders();
int random_beast(int n);
int random_trade_good();
int rc_to_region(int y, int x);
int read_spool(int mail_now);
int region_col(int i);
int region_row(int i);
int regular_combat(int, int, int, int);
void remove_comment(char *line);
void remove_ctrl_chars(char *line);
void rename_act_join_files();
int report_account_out(int pl, int who);
void reseed_monster_sublocs();
int reset_cast_where(int who);
void restore_stack_actions(int who);;
int savage_hates(int where);
void save_box(FILE *fp, int a);
void save_db();
void save_logdir();
void save_player_orders(int pl);
void scan_char_item_lore();
void scan_char_skill_lore();
void seed_city(int where);
void seed_city_near_lists();
void seed_city_trade(int where);
void seed_common_tradegoods();
void seed_cookies();
void seed_initial_locations();
void seed_monster_sublocs();
void seed_orcs();
void seed_population();
void seed_rare_tradegoods();
void seed_taxes();
int select_attacker(int who, int target);
int send_rep(int who, int turn);
void set_att(int who, int a, int attitude);
void set_bit(sparse *kr, int i);
void setup_html_all();
void setup_html_dir(int pl);
void set_html_pass(int pl);
void ship_storm_check(int ship);
int ship_cap(int ship);
void ship_summary(int pl);
void show_carry_capacity(int who, int who2);
void show_item_skills(int who, int who2);
void show_item_where(int who, int target);
void show_loc(int who, int where);
void show_loc_posts(int pl, int i, int boolean);
void show_lore_sheets();
void show_unclaimed(int i, int n);
char *sout(char *format, ...);
void sort_for_output(ilist l);
void stage(char *s);
int starting_noble_points(int i);
void storm_report(int pl);
int sub_item(int where, int item, int something);
void summary_report();
int survive_fatal(int pris);
void tagout(int who, char *format, ...);
void tags_off();
void tags_on();
int test_bit(sparse kr, int i);
int test_random(void);
void text_list_free(char **l);
void touch_loc_after_move(int who, int where);
void trade_suffuse_ring(int where);
void update_faery();
void update_markets();
void weekly_prisoner_escape_check();
int will_accept(int target, int item, int who, int qty);
int will_admit(int pl, int who, int ruler);
void wiout(int who, int ind, char *format, ...);
void wout(int who, char *format, ...);
void write_email();
void write_factions();
void write_forwards();
void write_player(int pl);
void write_nations_lists();
void write_player_list();
void write_totimes();
void update_city_trade(int where, int action, int item, int qty, int base_price, int n);
void update_weather_view_locs(int who, int where);
int v_art_crown(struct command *c);
int v_art_destroy(struct command *c);
int v_art_orb(struct command *c);
int v_art_teleport(struct command *c);
int v_collect(struct command *c);
int v_format(struct command *c);
int v_identify(struct command *c);
int v_move_attack(struct command *c);
int v_notab(struct command *c);
int v_power_jewel(struct command *c);
int v_practice(struct command *c);
int v_study(struct command *c), d_study(struct command *c);
int v_summon_aid(struct command *c);
int v_teach(struct command *c), d_teach(struct command *c);
int v_use_death(struct command *c);
int v_use_drum(struct command *c);
int v_use_faery_artifact(struct command *c);
int v_use_fiery(struct command *c);
int v_use_heal(struct command *c);
int v_use_item(struct command *c);
int v_use_orb(struct command *c);
int v_use_proj_cast(struct command *c);
int v_use_quick_cast(struct command *c);
int v_use_slave(struct command *c);
int v_use_weightlessness(struct command *c);
void vector_players();

// mdhender: bulk from use.c
int v_attack_tactics(struct command *);
int v_defense_tactics(struct command *);
int v_prac_control(struct command *);
int v_prac_protect(struct command *);
int v_use_beasts(struct command *);
int v_sail(struct command *), d_sail(struct command *), i_sail(struct command *);
int v_brew(struct command *), d_brew_heal(struct command *), d_brew_death(struct command *);
int d_brew_slave(struct command *), d_brew_fiery(struct command *);
int d_brew_weightlessness(struct command *);
int v_add_ram(struct command *), d_add_ram(struct command *);
int v_remove_ram(struct command *), d_remove_ram(struct command *);
int v_wood(struct command *), v_yew(struct command *), v_catch(struct command *);
int v_spy_inv(struct command *), d_spy_inv(struct command *), v_spy_lord(struct command *), d_spy_lord(struct command *);
int v_spy_skills(struct command *), d_spy_skills(struct command *);
int v_adv_med(struct command *), d_adv_med(struct command *);
int v_hinder_med(struct command *), d_hinder_med(struct command *);
int v_defense(struct command *), d_defense(struct command *);
int v_archery(struct command *), d_archery(struct command *);
int v_swordplay(struct command *), d_swordplay(struct command *);
int v_detect_gates(struct command *), d_detect_gates(struct command *), v_jump_gate(struct command *), v_teleport(struct command *);
int v_reverse_jump(struct command *), v_reveal_key(struct command *), d_reveal_key(struct command *);
int v_seal_gate(struct command *), d_seal_gate(struct command *), v_unseal_gate(struct command *), d_unseal_gate(struct command *);
int v_notify_unseal(struct command *), d_notify_unseal(struct command *), v_rem_seal(struct command *), d_rem_seal(struct command *);
int v_notify_jump(struct command *), d_notify_jump(struct command *), v_meditate(struct command *), d_meditate(struct command *);
int v_heal(struct command *), d_heal(struct command *), v_reveal_mage(struct command *), d_reveal_mage(struct command *), v_appear_common(struct command *);
int v_view_aura(struct command *), d_view_aura(struct command *), v_shroud_abil(struct command *), d_shroud_abil(struct command *);
int v_detect_abil(struct command *), d_detect_abil(struct command *), v_detect_scry(struct command *), d_detect_scry(struct command *);
int v_scry_region(struct command *), d_scry_region(struct command *), v_shroud_region(struct command *), d_shroud_region(struct command *);
int v_dispel_region(struct command *), d_dispel_region(struct command *), v_dispel_abil(struct command *), d_dispel_abil(struct command *);
int v_proj_cast(struct command *), d_proj_cast(struct command *), v_locate_char(struct command *), d_locate_char(struct command *);
int v_bar_loc(struct command *), d_bar_loc(struct command *), v_unbar_loc(struct command *), d_unbar_loc(struct command *);
int v_forge_palantir(struct command *), d_forge_palantir(struct command *);
int v_destroy_art(struct command *), d_destroy_art(struct command *);
int v_show_art_creat(struct command *), d_show_art_creat(struct command *);
int v_show_art_reg(struct command *), d_show_art_reg(struct command *);
int v_save_proj(struct command *), d_save_proj(struct command *);
int v_save_quick(struct command *), d_save_quick(struct command *);
int v_quick_cast(struct command *), d_quick_cast(struct command *);
int v_rem_art_cloak(struct command *), d_rem_art_cloak(struct command *);
int v_write_spell(struct command *), d_write_spell(struct command *);
int v_curse_noncreat(struct command *), d_curse_noncreat(struct command *);
int v_cloak_creat(struct command *), d_cloak_creat(struct command *);
int v_cloak_reg(struct command *), d_cloak_reg(struct command *);
int v_forge_aura(struct command *), d_forge_aura(struct command *);
int v_bribe(struct command *), d_bribe(struct command *);
int v_shipbuild(struct command *c);
int v_summon_savage(struct command *), v_keep_savage(struct command *), d_keep_savage(struct command *);
int v_improve_opium(struct command *), d_improve_opium(struct command *);
int v_lead_to_gold(struct command *), d_lead_to_gold(struct command *);
int v_raise(struct command *), d_raise(struct command *);
int v_rally(struct command *), d_rally(struct command *);
int v_incite(struct command *), d_incite(struct command *);
int v_bird_spy(struct command *), d_bird_spy(struct command *);
int v_eat_dead(struct command *), d_eat_dead(struct command *);
int v_raise_corpses(struct command *), v_undead_lord(struct command *), d_undead_lord(struct command *);
int v_banish_undead(struct command *), d_banish_undead(struct command *), v_keep_undead(struct command *), d_keep_undead(struct command *);
int v_aura_blast(struct command *), d_aura_blast(struct command *), v_aura_reflect(struct command *);
int v_banish_corpses(struct command *), d_banish_corpses(struct command *);
int v_summon_rain(struct command *), d_summon_rain(struct command *);
int v_summon_wind(struct command *), d_summon_wind(struct command *);
int v_summon_fog(struct command *), d_summon_fog(struct command *);
int v_dissipate(struct command *), d_dissipate(struct command *);
int v_direct_storm(struct command *), v_renew_storm(struct command *), d_renew_storm(struct command *);
int v_lightning(struct command *), d_lightning(struct command *);
int v_seize_storm(struct command *), d_seize_storm(struct command *);
int v_death_fog(struct command *), d_death_fog(struct command *);
int v_hide(struct command *), d_hide(struct command *);
int v_sneak(struct command *), d_sneak(struct command *);
int v_fierce_wind(struct command *), d_fierce_wind(struct command *);
int v_conceal_nation(struct command *), d_conceal_nation(struct command *);
int v_mage_menial(struct command *), d_mage_menial(struct command *);
int v_reveal_vision(struct command *), d_reveal_vision(struct command *);
int v_create_dirt_golem(struct command *), d_create_dirt_golem(struct command *);
int v_create_flesh_golem(struct command *), d_create_flesh_golem(struct command *);
int v_create_iron_golem(struct command *), d_create_iron_golem(struct command *);
int v_resurrect(struct command *), d_resurrect(struct command *);
int v_prep_ritual(struct command *), d_prep_ritual(struct command *);
int v_last_rites(struct command *), d_last_rites(struct command *);
int v_remove_bless(struct command *), d_remove_bless(struct command *);
int v_find_rich(struct command *), d_find_rich(struct command *);
int v_torture(struct command *), d_torture(struct command *);
int v_fight_to_death(struct command *);
int v_breed(struct command *), d_breed(struct command *);
int v_fish(struct command *);
int v_petty_thief(struct command *), d_petty_thief(struct command *), i_petty_thief(struct command *);
int v_persuade_oath(struct command *), d_persuade_oath(struct command *);
int v_forge_art_x(struct command *), d_forge_art_x(struct command *);
int v_trance(struct command *c), d_trance(struct command *c);
int v_teleport_item(struct command *), d_teleport_item(struct command *);
int v_tap_health(struct command *), d_tap_health(struct command *);
#if 0
int v_bind_storm(struct command *), d_bind_storm(struct command *);
#endif
int v_use_train_riding(struct command *), v_use_train_war(struct command *);
int v_assassinate(struct command *), d_assassinate(struct command *);
int v_find_food(struct command *), d_find_food(struct command *);
int v_generic_trap(struct command *), d_generic_trap(struct command *);
int v_bless_follower(struct command *), v_proselytise(struct command *), v_create_holy_symbol(struct command *);
int d_create_holy_symbol(struct command *);
int d_detect_beasts(struct command *), v_detect_beasts(struct command *);
int d_capture_beasts(struct command *), v_capture_beasts(struct command *);
int v_gather_holy_plant(struct command *), d_gather_holy_plant(struct command *);
int v_find_mountain_trail(struct command *), v_obscure_mountain_trail(struct command *);
int d_obscure_mountain_trail(struct command *);
int v_improve_mining(struct command *), d_improve_mining(struct command *);
int v_conceal_mine(struct command *), d_conceal_mine(struct command *);
int v_protect_mine(struct command *), d_protect_mine(struct command *);
int v_bless_fort(struct command *), d_bless_fort(struct command *);
int v_weaken_fort(struct command *), d_weaken_fort(struct command *);
int v_find_forest_trail(struct command *), d_obscure_forest_trail(struct command *), v_obscure_forest_trail(struct command *);
int d_improve_logging(struct command *), v_improve_logging(struct command *), d_find_hidden_features(struct command *);
int v_find_hidden_features(struct command *), v_improve_fort(struct command *), d_improve_fort(struct command *);
int v_recruit_elves(struct command *), d_recruit_elves(struct command *);
int d_improve_quarrying(struct command *), v_improve_quarrying(struct command *);
int d_improve_smithing(struct command *), v_improve_smithing(struct command *);
int d_edge_of_kireus(struct command *), v_edge_of_kireus(struct command *);
int d_create_mithril(struct command *), v_create_mithril(struct command *);
int v_enchant_guard(struct command *), d_enchant_guard(struct command *);
int v_urchin_spy(struct command *), d_urchin_spy(struct command *);
int v_draw_crowds(struct command *), d_draw_crowds(struct command *);
int v_arrange_mugging(struct command *), d_arrange_mugging(struct command *);
int d_calm_peasants(struct command *);
int v_improve_charisma(struct command *), d_improve_charisma(struct command *);
int d_mesmerize_crowd(struct command *);
int d_improve_taxes(struct command *);
int d_guard_loyalty(struct command *);
int d_instill_fanaticism(struct command *);
int d_find_all_hidden_features(struct command *);
int d_conceal_location(struct command *), v_conceal_location(struct command *);
int d_create_ninja(struct command *), v_create_ninja(struct command *);
int d_create_mist(struct command *);
int d_dedicate_temple(struct command *), v_dedicate_temple(struct command *);
int d_dedicate_tower(struct command *), v_dedicate_tower(struct command *);
int v_smuggle_goods(struct command *c), d_smuggle_goods(struct command *c), v_smuggle_men(struct command *c), d_smuggle_men(struct command *c), v_build_wagons(struct command *c), d_build_wagons(struct command *c), v_increase_demand(struct command *c), d_increase_demand(struct command *c), v_decrease_demand(struct command *c), d_decrease_demand(struct command *c), v_increase_supply(struct command *c), d_increase_supply(struct command *c), v_decrease_supply(struct command *c), d_decrease_supply(struct command *c), v_hide_money(struct command *c), d_hide_money(struct command *c), v_hide_item(struct command *c), d_hide_item(struct command *c);
int v_grow_pop(struct command *c), d_grow_pop(struct command *c);
int d_add_sails(struct command *c);
int v_add_sails(struct command *c);
int d_remove_sails(struct command *c);
int v_remove_sails(struct command *c);
int d_add_forts(struct command *c);
int v_add_forts(struct command *c);
int d_remove_forts(struct command *c);
int v_remove_forts(struct command *c);
int d_add_keels(struct command *c);
int v_add_keels(struct command *c);
int d_remove_keels(struct command *c);
int v_remove_keels(struct command *c);
int d_add_ports(struct command *c);
int v_add_ports(struct command *c);
int d_remove_ports(struct command *c);
int v_remove_ports(struct command *c);
int d_fortify_castle(struct command *c);
int v_fortify_castle(struct command *c);
int d_strengthen_castle(struct command *c);
int v_strengthen_castle(struct command *c);
int d_moat_castle(struct command *c);
int v_moat_castle(struct command *c);
int d_widen_entrance(struct command *c);
int v_widen_entrance(struct command *c);
int v_mine_iron(struct command *), d_mine_iron(struct command *), v_mine_gold(struct command *), d_mine_gold(struct command *);
int v_mine_mithril(struct command *), d_mine_mithril(struct command *), v_quarry(struct command *);
int v_mine_gate_crystal(struct command *), d_mine_gate_crystal(struct command *);
int d_add_wooden_shoring(struct command *), v_add_wooden_shoring(struct command *);
int d_add_iron_shoring(struct command *), v_add_iron_shoring(struct command *);
int v_mutate_art(struct command *);
int d_mutate_art(struct command *);
int v_conceal_arts(struct command *);
int d_conceal_arts(struct command *);
int v_detect_arts(struct command *);
int d_detect_arts(struct command *);
int v_obscure_art(struct command *);
int d_obscure_art(struct command *);
int v_unobscure_art(struct command *);
int d_unobscure_art(struct command *);
int v_reveal_arts(struct command *);
int d_reveal_arts(struct command *);
int v_deep_identify(struct command *);
int v_personal_fight_to_death(struct command *);
int v_forced_march(struct command *);
int v_hinder_med_b(struct command *), d_hinder_med_b(struct command *);
int v_vision_reg(struct command *), d_vision_reg(struct command *);
int v_use_cs(struct command *c);
int v_implicit(struct command *c);
int v_raze(struct command *), d_raze(struct command *);

// mdhender: temporary declarations to appease compiling on Windows with gcc
void bcopy(const void *src, void *dest, size_t n);
void bzero(void *s, size_t n);

long int random(void);
void srandom(unsigned int seed);

#endif //OLYTAG_FORWARD_H
