<!-- sidebar -->
<div id="left">
<ul>
<li><h3 align="center">Rules</h3>
  <ul>
  <li><a href="/rules">TAG Rules (browse online)</a></li>
  <li><a href="/rules/r.html">TAG Rules (one big file - downloadable)</a></li>
  </ul>
</li>
<li><h3 align="center">Guides</h3>
  <ul>
  <li><a href="/docs/newbiescrolls.php">The Newbie Scrolls</a> - a guide for new players in the TAG world.</li>
  <li><a href="/docs/tips.php">Quick Tips for New Players</a></li>
  <li><a href="/docs/makingmoney.php">Making Money</a></li>
  <li><a href="/docs/tagprimer.php">TAG Primer for G2(G3) Players</a> </li>
  </ul>
</li>
<li><h3 align="center">Playtest Game</h3>
  <ul>
  <li><a href="http://olympia.v-labs.be/forum/viewtopic.php?f=20&t=215">Sign up information</a></li>
  <li><a href="http://olympia.v-labs.be/forum/viewforum.php?f=20">Discussion Forum</a></li>
  <li><a href="../public/info/map.html">Map (from moderator test faction reports)</a></li>
  </ul>

</li>
</ul>
</div><!-- end sidebar -->


